services:
  - type: web
    name: warehouse-telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python warehouse.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: warehouse-db
          property: connectionString
      - key: RENDER
        value: true
